### ISSUE TITLE
Add support for dynamic account/profile switching

### ISSUE THREAD

**Issue by tevert** [bwhaley/ssmsh#10]
Currently, I frequently switch between AWS accounts by exiting, resetting `AWS_PROFILE`, and restarting. It would be kind of cool if I could do that in-shell with a `profile` command or something like that. I'd expect to stay at the same level in the parameter path hierarchy, unless that path doesn't exist of course, in which case I'd like to be bumped up until it does exist and shown a warning about it

Thanks for your work, this is an awesome tool!

**Comment by bwhaley** [comment]
This is something I'd definitely like to add. I'm busy with summer vacation currently but should have a chance to work on this later next month. Thanks for your request!

**Comment by bwhaley** [comment]
Added a profile command in the 1.3.2 release 🥇
