### ISSUE TITLE
Deep copy nests incorrectly

### ISSUE THREAD

**Issue by toddiuszho** [bwhaley/ssmsh#11]
I have a huge hierarchy under `/test` I wanted to duplicate under `/alpha` (which previously didn't exist). I did `cp -R /test /alpha`, but it unexpectedly created `/alpha/test`, with the source hierarchy under that path, instead of under just `/alpha`.

```
$ ssmsh --version
Version 1.3
```

This is for darwin-amd64, which I grabbed from GitHub Releases.

**Comment by bwhaley** [comment]
Thanks for your report! I've fixed this in the last commit. Will push a new release out momentarily.
