### ISSUE TITLE
Include key id in parameter get

### ISSUE THREAD

**Issue by kenske** [bwhaley/ssmsh#13]
It would be nice if the `get` command would return the parameter key id in the response.

**Comment by bwhaley** [comment]
Hi @kenske, thanks for submitting this. The tool uses the AWS Systems Manager `[GetParameter](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameter.html)` API which doesn't return the KMS key. Perhaps unintuitively, the `[history](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameterHistory.html)` command does return the key name. Will this work for your use case?

**Comment by kenske** [comment]
Yeah, that works!
It's also available in `describe-parameters`:
```
aws ssm describe-parameters --filter Key=Name,Values=/namespace/foo
```

Not sure what's easier to use.

**Comment by bwhaley** [comment]
Cool - since `history` is already there, and `describe` is somewhat redundant with `get`, I'll recommend `history` to you for the time being. But perhaps `ssmsh` really should also support `describe`. I'll ponder that one. Thanks!

**Comment by kenske** [comment]
Maybe `get` should merge the responses from both `GetParameter` and `DescribeParameters`
