### ISSUE TITLE
Feature:  allow setting default type and default overwrite value

### ISSUE THREAD

**Issue by slimm609** [bwhaley/ssmsh#14]
When using ssmsh to update lots of values, having to type  type="SecureString" and overwrite=true, allow setting a session default value like decrypt option, so that type and overwrite could be left off of each put request.

**Comment by slimm609** [comment]
one other thing that would be nice to have is a ~/.ssmshrc file that has defaults 

e.g.
```txt
decrypt=true
overwrite=true
type=securestring
```
that could persist between sessions.

**Comment by bwhaley** [comment]
Thanks for the compliment. I will implement both of these ideas when I have a chance.

**Comment by bwhaley** [comment]
I've added support for setting defaults in a configuration file. [Refer to the README](https://github.com/bwhaley/ssmsh#configuration). 🎉

**Comment by slimm609** [comment]
Tested the 1.4.0 release and it is working great.   used it for over 100 SSM parameters and no issues.

**Comment by bwhaley** [comment]
Thank you for testing it out!
