### ISSUE TITLE
error out and exit when `Key` without any parameters 

### ISSUE THREAD

**Issue by donglaizhang** [bwhaley/ssmsh#17]
Hey,
Thank you for contributing this cool cli tool for managing Parameter-store. Here is one small issue.
when running `key` without any parameter, `ssm` will exit with `golang` stack trace error information.

**Comment by bwhaley** [comment]
Thanks for filing this! Fix available in [v1.4.1](https://github.com/bwhaley/ssmsh/releases/tag/v1.4.1).
