### ISSUE TITLE
Super slow performance in ConEmu

### ISSUE THREAD

**Issue by tevert** [bwhaley/ssmsh#18]
This is a pretty niche issue, so no hard feelings if you want just ignore this one as an unsupported configuration

I use https://conemu.github.io/ on Windows as my day-to-day shell. I have it configured to launch WSL's bash with: `set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & wsl -d ubuntu -u tevert -cur_console:t:"Ubuntu" -- bash -l -i` 

When running ssmsh (`Version 1.3.2`) in a standalone `bash` window, it's totally fine. In ConEmu, it takes almost a full second for each typed character to appear, and the whole line flickers while doing so

**Comment by bwhaley** [comment]
Hmm, I'd have to reproduce this one to properly debug it. Might be an issue upstream in the CLI abiosoft/ishell library.

**Comment by tevert** [comment]
This got resolved at some point, upgrading ConEmu last month seems to have eliminated this

**Comment by bwhaley** [comment]
Thanks for closing the loop!
