### ISSUE TITLE
Native way to query parameter's value from get operation

### ISSUE THREAD

**Issue by maishiroma** [bwhaley/ssmsh#22]
Hello! I stumbled across your repository while looking for clean CLI wrappers for interacting with AWS SSM and this tool is really promising! Been experimenting with this and I noticed that in the `get` operation, there isn't a native way to only extract the value from the output.
```
$ ssmsh get /some/parameter/ 
[{                                                                                                                       
  ARN: "...",                                              
  LastModifiedDate: 2020-07-29 16:15:51 +0000 UTC,                                                                       
  Name: "/some/parameter",                                                                                         
  Type: "String",                                                                                                  
  Value: "someValue",                                                                                                               
  Version: 1                                                                                                             
}]
```

The reason I'm asking this is because I would like to utilize this in a bash script where I parse out the parameter's value into an environment/local variable. While I was able to obtain my desired behavior with `grep` and `cut`:
```
ssmsh  get /some/parameter | grep Value | cut -d "\"" -f 2
```
I think having the output to be native JSON would help in terms of usability. Maybe having a way to specify the output type in the `.ssmsh` config could be one way to offer the flexibility of this?

**Comment by bwhaley** [comment]
Good idea! Is the thinking that you'd then be able to extract the value more cleanly with `jq`? Right now it's just printing the Go object, and it does seem like JSON would be useful.

**Comment by maishiroma** [comment]
> Is the thinking that you'd then be able to extract the value more cleanly with `jq`?

Yup! That was exactly was what I was thinking. Either that tool or any tool that can take in json input, but at least for the case I'm thinking, I would use `jq` to extract a value out of the JSON object.

**Comment by bwhaley** [comment]
Added JSON output functionality for `get` and `history` commands. Complete JSON support (e.g. for `ls` and other commands) is more time that I can commit right at the moment, but hopefully this lazy stopgap will help. Let me know if this will work for you!

[`Release v1.4.3`](https://github.com/bwhaley/ssmsh/releases/tag/v1.4.3).

**Comment by maishiroma** [comment]
@bwhaley Thank you so much for looking into this issue! I just tested this on my end and it works like a charm! My only critique would that it puts the JSON output in a list, so you'd need to index the value out of said list, but besides that, it made querying the value so much easier now.

I also appreciate you considering fully supporting JSON output for all of the operations. At the time of this issue, I only saw the value in JSON output for the `get` operation, so this new feature is already a good step forward! Having a potential issue/future issue for JSON output is a good wish list item for the time being, especially to keep the consistency with the config for all operations. 

Regardless, thanks again for adding this into the latest release! I'll go ahead and close this issue now since this is now supported. 😄

**Comment by bwhaley** [comment]
I'm glad this worked out for you!

> My only critique would that it puts the JSON output in a list

The reason for this is that `get` supports retrieving multiple parameters in one command, e.g.

```
> ssmsh get /foo/bar /foo/bar2
```

In which case the results would necessarily be a list. 

Anyway, thanks for the feature request!

**Comment by maishiroma** [comment]
Ah I see that makes sense, I apologize for not noticing that in your changes! Thanks for clarifying on that. 😄
