### ISSUE TITLE
Contributing a Homebrew package

### ISSUE THREAD

**Issue by dbirks** [bwhaley/ssmsh#26]
Hi, I saw the to-do to release via Homebrew, and I was wanting to contribute that if I could. 

I could create the Homebrew package manually, or I've also seen that goreleaser can create one:
https://goreleaser.com/customization/homebrew/

Would you be interested in a PR to add goreleaser to the Github Actions? I've been wanting to learn both homebrew packaging and goreleaser, and this looks like a good opportunity to learn both. :slightly_smiling_face:

**Comment by bwhaley** [comment]
Yes, that would be fantastic, and a most welcome contribution!

**Comment by dbirks** [comment]
Awesome! I'll see if I can do that sometime in the next couple weeks :turkey:
