### ISSUE TITLE
ValidationException about the parameter name on Windows

### ISSUE THREAD

**Issue by mtmelvin** [bwhaley/ssmsh#32]
I'm using the Windows binaries and running into an issue doing mostly anything with ssmsh.

The error is: 
```
Error:  ValidationException: The parameter doesn't meet the parameter name requirements. The parameter name must begin with a forward slash "/". It can't be prefixed with \"aws\" or \"ssm\" (case-insensitive). It must use only letters, numbers, or the following symbols: . (period), - (hyphen), _ (underscore). Special characters are not allowed. All sub-paths, if specified, must use the forward slash symbol "/". Valid example: /get/parameters2-/by1./path0_.
```

Some quick debugging found that the [fqp function in parameterstore.go](https://github.com/bwhaley/ssmsh/blob/4369ee21a34b52f5d6de08fcde30aa7192fa34d7/parameterstore/parameterstore.go#L491-L501) is using `filepath.Clean` to clean up the parameter paths. On Windows, `filepath.Clean` replaces `/` with `\`, which breaks the query to SSM.

I know that at some point, the request validation for S3 became more strict and it stopped working with `\` as a delimiter. I suspect the same happened for Parameter Store.

After switching usage to [path.Clean](https://pkg.go.dev/path#Clean), it seems to work fine, but I wasn't sure if you were using `filepath.Clean` instead intentionally due to some other issues.

I'll be happy to submit a PR if you like. It's not a very big change.

**Comment by bwhaley** [comment]
Fixed in #33
